### ISSUE TITLE
Apple Macs and Google Home doesnt get IP or very delayed.

### ISSUE THREAD

**Issue by oe3gwu** [homeall/dhcphelper#2]
**Describe the bug**
A Apple Mac with get an IP quick, looses it again and after 30 seconds will get the same IP again. A Google Home doesnt even get an IP at all.

**To Reproduce**
1. Deploy the stack
2. Enable DHCP on Pi Hole
3. Test the system

**Expected behavior**
Stable and fast deployment of IP's.

**Desktop (please complete the following information):**
 - Apple Macbook Air M1 with Mavericks
 - Google Home Mini

**Additional context**
It seems to be a topic with the dhcphelper. Using only Pi Hole in Host Mode works well.

**Comment by ionutz89** [comment]
I do not see this issue on my setup. Also this is only DHCP relay, not the actually DHCP server like Pi-Hole. Did you check your logs? Also did you try to use only dhpchelper on other ubuntu server and try to replicate.
